class BaseSarvException(Exception): ...

class SarvServerError(BaseSarvException):
    '''
    SarvCRM Server Exception
    '''
    class ItemNotFound(BaseSarvException): ...
    class ModuleNotFound(BaseSarvException): ...
    class MYSQLError(BaseSarvException): ...
    class RequiredField(BaseSarvException): ...