class BaseSarvException(Exception): ...

class SarvServerErrors(BaseSarvException):
    '''
    SarvCRM Server Exception
    '''
    class ItemNotFound(BaseSarvException): ...
    class ModuleNotFound(BaseSarvException): ...
    class MYSQLError(BaseSarvException): ...
    class RequiredField(BaseSarvException): ...
    class UnsupportedMethod(BaseSarvException): ...